version: '2'
services:
    internshipping-app:
        image: internshipping
        external_links:
            - internshipping-mysql:mysql
            - internshipping-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/internshipping?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    internshipping-mysql:
        extends:
            file: mysql.yml
            service: internshipping-mysql
    internshipping-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: internshipping-elasticsearch
